<?php  
if ( ! defined( 'ABSPATH' ) ) exit; // Exit if accessed directly

class Woolentor_Icon_List{

    /**
     * [get_icons]
     * @return [array]
     */
    public static function get_icons(){
        $simple_line_icon = [
            'sli-user' => 'sli sli-user',
            'sli-people' => 'sli sli-people',
            'sli-user-female' => 'sli sli-user-female',
            'sli-user-follow' => 'sli sli-user-follow',
            'sli-user-following' => 'sli sli-user-following',
            'sli-user-unfollow' => 'sli sli-user-unfollow',
            'sli-login' => 'sli sli-login',
            'sli-logout' => 'sli sli-logout',
            'sli-emotsmile' => 'sli sli-emotsmile',
            'sli-phone' => 'sli sli-phone',
            'sli-call-end' => 'sli sli-call-end',
            'sli-call-in' => 'sli sli-call-in',
            'sli-call-out' => 'sli sli-call-out',
            'sli-map' => 'sli sli-map',
            'sli-location-pin' => 'sli sli-location-pin',
            'sli-direction' => 'sli sli-direction',
            'sli-directions' => 'sli sli-directions',
            'sli-compass' => 'sli sli-compass',
            'sli-layers' => 'sli sli-layers',
            'sli-menu' => 'sli sli-menu',
            'sli-list' => 'sli sli-list',
            'sli-options-vertical' => 'sli sli-options-vertical',
            'sli-options' => 'sli sli-options',
            'sli-arrow-down' => 'sli sli-arrow-down',
            'sli-arrow-left' => 'sli sli-arrow-left',
            'sli-arrow-right' => 'sli sli-arrow-right',
            'sli-arrow-up' => 'sli sli-arrow-up',
            'sli-arrow-up-circle' => 'sli sli-arrow-up-circle',
            'sli-arrow-left-circle' => 'sli sli-arrow-left-circle',
            'sli-arrow-right-circle' => 'sli sli-arrow-right-circle',
            'sli-arrow-down-circle' => 'sli sli-arrow-down-circle',
            'sli-check' => 'sli sli-check',
            'sli-clock' => 'sli sli-clock',
            'sli-plus' => 'sli sli-plus',
            'sli-minus' => 'sli sli-minus',
            'sli-close' => 'sli sli-close',
            'sli-event' => 'sli sli-event',
            'sli-exclamation' => 'sli sli-exclamation',
            'sli-organization' => 'sli sli-organization',
            'sli-trophy' => 'sli sli-trophy',
            'sli-screen-smartphone' => 'sli sli-screen-smartphone',
            'sli-screen-desktop' => 'sli sli-screen-desktop',
            'sli-plane' => 'sli sli-plane',
            'sli-notebook' => 'sli sli-notebook',
            'sli-mustache' => 'sli sli-mustache',
            'sli-mouse' => 'sli sli-mouse',
            'sli-magnet' => 'sli sli-magnet',
            'sli-energy' => 'sli sli-energy',
            'sli-disc' => 'sli sli-disc',
            'sli-cursor' => 'sli sli-cursor',
            'sli-cursor-move' => 'sli sli-cursor-move',
            'sli-crop' => 'sli sli-crop',
            'sli-chemistry' => 'sli sli-chemistry',
            'sli-speedometer' => 'sli sli-speedometer',
            'sli-shield' => 'sli sli-shield',
            'sli-screen-tablet' => 'sli sli-screen-tablet',
            'sli-magic-wand' => 'sli sli-magic-wand',
            'sli-hourglass' => 'sli sli-hourglass',
            'sli-graduation' => 'sli sli-graduation',
            'sli-ghost' => 'sli sli-ghost',
            'sli-game-controller' => 'sli sli-game-controller',
            'sli-fire' => 'sli sli-fire',
            'sli-eyeglass' => 'sli sli-eyeglass',
            'sli-envelope-open' => 'sli sli-envelope-open',
            'sli-envelope-letter' => 'sli sli-envelope-letter',
            'sli-bell' => 'sli sli-bell',
            'sli-badge' => 'sli sli-badge',
            'sli-anchor' => 'sli sli-anchor',
            'sli-wallet' => 'sli sli-wallet',
            'sli-vector' => 'sli sli-vector',
            'sli-speech' => 'sli sli-speech',
            'sli-puzzle' => 'sli sli-puzzle',
            'sli-printer' => 'sli sli-printer',
            'sli-present' => 'sli sli-present',
            'sli-playlist' => 'sli sli-playlist',
            'sli-pin' => 'sli sli-pin',
            'sli-picture' => 'sli sli-picture',
            'sli-handbag' => 'sli sli-handbag',
            'sli-globe-alt' => 'sli sli-globe-alt',
            'sli-globe' => 'sli sli-globe',
            'sli-folder-alt' => 'sli sli-folder-alt',
            'sli-folder' => 'sli sli-folder',
            'sli-film' => 'sli sli-film',
            'sli-feed' => 'sli sli-feed',
            'sli-drop' => 'sli sli-drop',
            'sli-drawer' => 'sli sli-drawer',
            'sli-docs' => 'sli sli-docs',
            'sli-doc' => 'sli sli-doc',
            'sli-diamond' => 'sli sli-diamond',
            'sli-cup' => 'sli sli-cup',
            'sli-calculator' => 'sli sli-calculator',
            'sli-bubbles' => 'sli sli-bubbles',
            'sli-briefcase' => 'sli sli-briefcase',
            'sli-book-open' => 'sli sli-book-open',
            'sli-basket-loaded' => 'sli sli-basket-loaded',
            'sli-basket' => 'sli sli-basket',
            'sli-bag' => 'sli sli-bag',
            'sli-action-undo' => 'sli sli-action-undo',
            'sli-action-redo' => 'sli sli-action-redo',
            'sli-wrench' => 'sli sli-wrench',
            'sli-umbrella' => 'sli sli-umbrella',
            'sli-trash' => 'sli sli-trash',
            'sli-tag' => 'sli sli-tag',
            'sli-support' => 'sli sli-support',
            'sli-frame' => 'sli sli-frame',
            'sli-size-fullscreen' => 'sli sli-size-fullscreen',
            'sli-size-actual' => 'sli sli-size-actual',
            'sli-shuffle' => 'sli sli-shuffle',
            'sli-share-alt' => 'sli sli-share-alt',
            'sli-share' => 'sli sli-share',
            'sli-rocket' => 'sli sli-rocket',
            'sli-question' => 'sli sli-question',
            'sli-pie-chart' => 'sli sli-pie-chart',
            'sli-pencil' => 'sli sli-pencil',
            'sli-note' => 'sli sli-note',
            'sli-loop' => 'sli sli-loop',
            'sli-home' => 'sli sli-home',
            'sli-grid' => 'sli sli-grid',
            'sli-graph' => 'sli sli-graph',
            'sli-microphone' => 'sli sli-microphone',
            'sli-music-tone-alt' => 'sli sli-music-tone-alt',
            'sli-music-tone' => 'sli sli-music-tone',
            'sli-earphones-alt' => 'sli sli-earphones-alt',
            'sli-earphones' => 'sli sli-earphones',
            'sli-equalizer' => 'sli sli-equalizer',
            'sli-like' => 'sli sli-like',
            'sli-dislike' => 'sli sli-dislike',
            'sli-control-start' => 'sli sli-control-start',
            'sli-control-rewind' => 'sli sli-control-rewind',
            'sli-control-play' => 'sli sli-control-play',
            'sli-control-pause' => 'sli sli-control-pause',
            'sli-control-forward' => 'sli sli-control-forward',
            'sli-control-end' => 'sli sli-control-end',
            'sli-volume-1' => 'sli sli-volume-1',
            'sli-volume-2' => 'sli sli-volume-2',
            'sli-volume-off' => 'sli sli-volume-off',
            'sli-calendar' => 'sli sli-calendar',
            'sli-bulb' => 'sli sli-bulb',
            'sli-chart' => 'sli sli-chart',
            'sli-ban' => 'sli sli-ban',
            'sli-bubble' => 'sli sli-bubble',
            'sli-camrecorder' => 'sli sli-camrecorder',
            'sli-camera' => 'sli sli-camera',
            'sli-cloud-download' => 'sli sli-cloud-download',
            'sli-cloud-upload' => 'sli sli-cloud-upload',
            'sli-envelope' => 'sli sli-envelope',
            'sli-eye' => 'sli sli-eye',
            'sli-flag' => 'sli sli-flag',
            'sli-heart' => 'sli sli-heart',
            'sli-info' => 'sli sli-info',
            'sli-key' => 'sli sli-key',
            'sli-link' => 'sli sli-link',
            'sli-lock' => 'sli sli-lock',
            'sli-lock-open' => 'sli sli-lock-open',
            'sli-magnifier' => 'sli sli-magnifier',
            'sli-magnifier-add' => 'sli sli-magnifier-add',
            'sli-magnifier-remove' => 'sli sli-magnifier-remove',
            'sli-paper-clip' => 'sli sli-paper-clip',
            'sli-paper-plane' => 'sli sli-paper-plane',
            'sli-power' => 'sli sli-power',
            'sli-refresh' => 'sli sli-refresh',
            'sli-reload' => 'sli sli-reload',
            'sli-settings' => 'sli sli-settings',
            'sli-star' => 'sli sli-star',
            'sli-symbol-female' => 'sli sli-symbol-female',
            'sli-symbol-male' => 'sli sli-symbol-male',
            'sli-target' => 'sli sli-target',
            'sli-credit-card' => 'sli sli-credit-card',
            'sli-paypal' => 'sli sli-paypal',
            'sli-social-tumblr' => 'sli sli-social-tumblr',
            'sli-social-twitter' => 'sli sli-social-twitter',
            'sli-social-facebook' => 'sli sli-social-facebook',
            'sli-social-instagram' => 'sli sli-social-instagram',
            'sli-social-linkedin' => 'sli sli-social-linkedin',
            'sli-social-pinterest' => 'sli sli-social-pinterest',
            'sli-social-github' => 'sli sli-social-github',
            'sli-social-google' => 'sli sli-social-google',
            'sli-social-reddit' => 'sli sli-social-reddit',
            'sli-social-skype' => 'sli sli-social-skype',
            'sli-social-dribbble' => 'sli sli-social-dribbble',
            'sli-social-behance' => 'sli sli-social-behance',
            'sli-social-foursqare' => 'sli sli-social-foursqare',
            'sli-social-soundcloud' => 'sli sli-social-soundcloud',
            'sli-social-spotify' => 'sli sli-social-spotify',
            'sli-social-stumbleupon' => 'sli sli-social-stumbleupon',
            'sli-social-youtube' => 'sli sli-social-youtube',
            'sli-social-dropbox' => 'sli sli-social-dropbox',
            'sli-social-vkontakte' => 'sli sli-social-vkontakte',
            'sli-social-steam' => 'sli sli-social-steam',
        ];

        $all_icon = array_merge( $simple_line_icon );
        return $all_icon;
    }
    
    public static function icon_sets(){

        $icon_set = [];
        $sinple_line = self::get_icons();

        foreach( $sinple_line as $key => $icon ) {
            $icon_set['SimpleLineIcon'][] = $icon;
        }
        return $icon_set;
    }


}